const ONE_HOUR_IN_SECONDS = 3600;
export const ONE_HOUR_IN_MILLISECONDS = ONE_HOUR_IN_SECONDS * 1000;
export const FIVE_MINUTES_IN_MILLISECONDS = 300000;

export const ANIMATE_TO_PARTY_DURATION = 300;
